bin/test-corpus: Add Hacklang tests

diff --git a/bin/test-corpus b/bin/test-corpus
--- a/bin/test-corpus
+++ b/bin/test-corpus
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e
+
 while [[ $# -gt 0 ]]; do
   case $1 in
   --force)
@@ -13,6 +15,13 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-bin/generate-parser $FORCE &&
-  bin/generate-corpus $FORCE &&
-  npx tree-sitter test
+printf "\033[1mRunning Tree-sitter tests...\033[0m\n"
+
+bin/generate-parser $FORCE
+bin/generate-corpus $FORCE
+
+npx tree-sitter test
+
+printf "\033[1mGetting Hacklang errors...\033[0m\n"
+
+bin/get-errors hack test/cases/**/*.php
